const express = require('express');
const router = express.Router();
const { searchRoutes, getAllRoutes, getRouteById, createRoute, updateRoute, deleteRoute, getPopularRoutes } = require('../controllers/routeController');
const { protect, authorize } = require('../middleware/auth');
router.get('/search', searchRoutes);
router.get('/popular', getPopularRoutes);
router.get('/', getAllRoutes);
router.get('/:id', getRouteById);
router.post('/', protect, authorize('admin'), createRoute);
router.put('/:id', protect, authorize('admin'), updateRoute);
router.delete('/:id', protect, authorize('admin'), deleteRoute);
module.exports = router;